import { environment } from "../../environments/environment";

export const URIS_CONFIG = {
    BASE_URI: environment.BASE_URL,
    SIGN_IN: 'auth',
    DASHBOARD: 'dashboard',
    USUARIOS: 'usuarios',
    ESTACIONES: 'estaciones',
    PROVEEDORES: 'proveedores',
    CLIENTES: 'clientes',
    TIPOS_CLIENTE: 'tipos-cliente',
    PRODUCTOS: 'productos',
    UBICACIONES: 'ubicaciones',
    CODIGOS_BARRAS: 'codigos-barras',
    LINEAS_PRODUCTO: 'lineas-producto',
    LIMITES_INVENTARIO: 'limites-inventario',
    RELACION_LIQUIDOS: 'relacion-liquidos',
    RELACION_TRAPEADORES: 'relacion-trapeadores',
    PRODUCCION_LIQUIDOS: 'produccion-liquidos',
    PRODUCCION_TRAPEADORES: 'produccion-trapeadores',
    COMPRAS: 'compras',
    EVALUACIONES: 'evaluaciones',
    ROLES: 'roles',
    LAYOUTS: 'layouts',
    CLAVES: 'claves',
    EVALUACIONES_ROLES: 'evaluaciones-roles',
    EVALUACION_ROL_TEMPLATE: 'evaluacion-rol-template',
    EVALUACIONES_ASIGNADAS: 'evaluaciones-asignadas',
    RESPUESTAS: 'respuestas',
    REPORTES: 'reportes',
    SYNC_DATA:'sync-data',
    PREGUNTAS_ESPECIALES: 'preguntas-especiales',
};
